// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  API: {
    GraphQL: {
      endpoint: import.meta.env.VITE_GraphQLAPI ?? '',
      region: 'eu-west-1',
      defaultAuthMode: 'apiKey',
    }
  }
};

export default config;