// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  API: {
    GraphQL: {
      endpoint: process.env.GraphQLAPIKey ?? '',
      region: 'eu-central-1',
      defaultAuthMode: 'apiKey',
    }
  }
};

export default config;