/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDialog: typeof import('./components/AddDialog.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreItem: typeof import('./components/ScoreItem.vue')['default']
    Top: typeof import('./components/Top.vue')['default']
    TopScoresList: typeof import('./components/TopScoresList.vue')['default']
  }
}
